[workspace]
members = ["libsabledb", "sabledb", "submodules/benchmark/common", "submodules/benchmark/sabledb-benchmark", "sdb-cli", "sdb-admin"]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
