site_name: SableDB
site_url: https://sabledb.io
repo_url: https://github.com/sabledb-io/sabledb
repo_name: GitHub
edit_uri: edit/main/docs/site

nav:
    - High Level Design: design/overview.md
    - Replication: design/replication.md
    - Auto Failover: design/auto-failover.md
    - Data encoding: design/data-encoding.md
    - Data eviction: design/eviction.md

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - content.code.copy
  palette:
    scheme: default
    primary: indigo
  highlightjs: true
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.keys
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  generator: false
